name: jungle
channels:
  - etetoolkit
  - bpteague
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports_abc=0.5=py27_0
  - biopython=1.74=py27h7b6447c_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py27_0
  - cycler=0.10.0=py27_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - enum34=1.1.6=py27_1
  - ete3=3.1.1=pyhf5214e1_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - functools32=3.2.3.2=py27_1
  - futures=3.3.0=py27_0
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2020.0=166
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.3.4=py27_0
  - jupyter_core=4.6.1=py27_0
  - kiwisolver=1.1.0=py27he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=4.4.1=py27hefd8a0e_0
  - matplotlib=2.2.3=py27hb69df0a_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py27he904b0f_0
  - mkl_fft=1.0.15=py27ha843d7b_0
  - mkl_random=1.1.0=py27hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.5=py27h7e9f1db_0
  - numpy-base=1.16.5=py27hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_4
  - pandas=0.24.2=py27he6710b0_0
  - pathlib2=2.3.5=py27_0
  - patsy=0.5.1=py27_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pip=19.2.3=py27_0
  - prompt_toolkit=1.0.15=py27_0
  - ptyprocess=0.6.0=py27_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py27h05f1152_2
  - python=2.7.17=h9bab390_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py27he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scandir=1.10.0=py27h7b6447c_0
  - scipy=1.2.1=py27h7c811a0_0
  - seaborn=0.9.0=py27_0
  - setuptools=41.4.0=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.12.0=py27_0
  - sqlite=3.31.1=h7b6447c_0
  - statsmodels=0.10.1=py27hdd07704_0
  - subprocess32=3.5.4=py27h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py27h7b6447c_0
  - traitlets=4.3.3=py27_0
  - wcwidth=0.1.8=py_0
  - wheel=0.33.6=py27_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
